input {
  generator {
    lines => [
      "ELK Swarm test event"
    ]
    count => 1
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-swarm-%{+YYYY.MM.dd}"
  }
}