input {
  heartbeat {
    interval => 60
    type => "swarm_test"
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-swarm-%{+YYYY.MM.dd}"
  }
}